name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
      with:
          submodules: true
    - name: Build glorytun
      run: |
          ./sodium.sh
          make prefix=. install

    - uses: actions/upload-artifact@v1
      with:
        name: bin
        path: ./bin
